// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIkM1okDawsBTlnVLytxKso8NsEDMjmpQ',
    appId: '1:60042785757:web:cf56119ec7f88f41c5fc34',
    messagingSenderId: '60042785757',
    projectId: 'apartment-ecosystem',
    authDomain: 'apartment-ecosystem.firebaseapp.com',
    storageBucket: 'apartment-ecosystem.firebasestorage.app',
    measurementId: 'G-HCL8336SQY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ8vu6r_R1JAEnpoT2ut91TTSeQ6GJ6hc',
    appId: '1:60042785757:android:e1141090635afef2c5fc34',
    messagingSenderId: '60042785757',
    projectId: 'apartment-ecosystem',
    storageBucket: 'apartment-ecosystem.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyqgcP_2WGVtyTY-VW0CI2YyQYjQfAYJ4',
    appId: '1:60042785757:ios:56314ea9ddbd193cc5fc34',
    messagingSenderId: '60042785757',
    projectId: 'apartment-ecosystem',
    storageBucket: 'apartment-ecosystem.firebasestorage.app',
    iosBundleId: 'com.example.apartmentEcosystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyqgcP_2WGVtyTY-VW0CI2YyQYjQfAYJ4',
    appId: '1:60042785757:ios:56314ea9ddbd193cc5fc34',
    messagingSenderId: '60042785757',
    projectId: 'apartment-ecosystem',
    storageBucket: 'apartment-ecosystem.firebasestorage.app',
    iosBundleId: 'com.example.apartmentEcosystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIkM1okDawsBTlnVLytxKso8NsEDMjmpQ',
    appId: '1:60042785757:web:64668e30fec96913c5fc34',
    messagingSenderId: '60042785757',
    projectId: 'apartment-ecosystem',
    authDomain: 'apartment-ecosystem.firebaseapp.com',
    storageBucket: 'apartment-ecosystem.firebasestorage.app',
    measurementId: 'G-3V1L1G87MM',
  );
}
